[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración para la regeneración estática incremental (ISR)
[functions]
  included_files = [".next/server/**"]
